services:
  postgres:
    image: postgres:15
    container_name: postgres_nest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT1}:${DB_PORT2}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  postgres_data:

networks:
  nest-network:
    driver: bridge